language: python
python:
- '2.7'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_f49fbc710c69_key -iv $encrypted_f49fbc710c69_iv -in id_ed25519.enc -out ~/.ssh/id_ed25519 -d
- chmod 400 ~/.ssh/id_ed25519

